eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka
    instance:
        preferIpAddress: true
security:
  basic:
    enabled: false

spring:
  boot:
    admin:
      url: http://admin-server:8080

management:
  security:
    enabled: false