eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8080/eureka
    instance:
        preferIpAddress: false
        hostname: 172.255.152.115
        ip-address: 127.0.0.1

security:
  basic:
    enabled: false

spring:
  boot:
    admin:
      url: http://admin-server:8080

management:
  security:
    enabled: false

keycloak:
  credentials:
    secret: 34dba647-7fbb-43f6-8691-c22baaae9507
  auth-server-url: http://172.255.152.115:8888/auth
  realm: apft
  ssl-required: external
  resource: purchase-service
