eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8080/eureka
    instance:
        preferIpAddress: true

spring:
  boot:
    admin:
      url: http://admin-server:8080

zuul:
  sensitive-headers: Authorization

management:
  security:
    enabled: false