eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka
    instance:
        preferIpAddress: true

zuul:
  routes:
    purchases:
      path: /purchase/**
      serviceId: purchase-service

spring:
  boot:
    admin:
      url: http://admin-server:8080

management:
  security:
    enabled: false